codecov:
  require_ci_to_pass: true

ignore:
  - "src/decaylanguage/__main__.py"
  - "src/decaylanguage/__init__.py"
  - "src/decaylanguage/*/__init__.py"
  - "src/decaylanguage/dec/decparser.py"
  - "src/decaylanguage/modeling/*"
  - "src/decaylanguage/utils/errors.py"
  - "src/decaylanguage/utils/utilities.py"
